# Generated by Django 3.1.1 on 2020-10-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travel_start', models.DateField()),
                ('travel_end', models.DateField()),
                ('desc', models.TextField()),
                ('planned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='belt_examApp.user')),
                ('users_joining', models.ManyToManyField(related_name='users', to='belt_examApp.User')),
            ],
        ),
    ]
